<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- NewPage -->
<html lang="pl">
<head>
<!-- Generated by javadoc (version 1.7.0_72) on Sat Nov 08 15:43:20 CET 2014 -->
<meta http-equiv="Content-Type" content="text/html" charset="UTF-8">
<title>CatchException (catch-exception 1.3.2 API)</title>
<meta name="date" content="2014-11-08">
<link rel="stylesheet" type="text/css" href="../../../stylesheet.css" title="Style">
</head>
<body>
<script type="text/javascript"><!--
    if (location.href.indexOf('is-external=true') == -1) {
        parent.document.title="CatchException (catch-exception 1.3.2 API)";
    }
//-->
</script>
<noscript>
<div>JavaScript is disabled on your browser.</div>
</noscript>
<!-- ========= START OF TOP NAVBAR ======= -->
<div class="topNav"><a name="navbar_top">
<!--   -->
</a><a href="#skip-navbar_top" title="Skip navigation links"></a><a name="navbar_top_firstrow">
<!--   -->
</a>
<ul class="navList" title="Navigation">
<li><a href="../../../overview-summary.html">Overview</a></li>
<li><a href="package-summary.html">Package</a></li>
<li class="navBarCell1Rev">Class</li>
<li><a href="class-use/CatchException.html">Use</a></li>
<li><a href="package-tree.html">Tree</a></li>
<li><a href="../../../deprecated-list.html">Deprecated</a></li>
<li><a href="../../../index-all.html">Index</a></li>
<li><a href="../../../help-doc.html">Help</a></li>
</ul>
</div>
<div class="subNav">
<ul class="navList">
<li>Prev Class</li>
<li><a href="../../../com/googlecode/catchexception/ExceptionNotThrownAssertionError.html" title="class in com.googlecode.catchexception"><span class="strong">Next Class</span></a></li>
</ul>
<ul class="navList">
<li><a href="../../../index.html?com/googlecode/catchexception/CatchException.html" target="_top">Frames</a></li>
<li><a href="CatchException.html" target="_top">No Frames</a></li>
</ul>
<ul class="navList" id="allclasses_navbar_top">
<li><a href="../../../allclasses-noframe.html">All Classes</a></li>
</ul>
<div>
<script type="text/javascript"><!--
  allClassesLink = document.getElementById("allclasses_navbar_top");
  if(window==top) {
    allClassesLink.style.display = "block";
  }
  else {
    allClassesLink.style.display = "none";
  }
  //-->
</script>
</div>
<div>
<ul class="subNavList">
<li>Summary:&nbsp;</li>
<li>Nested&nbsp;|&nbsp;</li>
<li>Field&nbsp;|&nbsp;</li>
<li><a href="#constructor_summary">Constr</a>&nbsp;|&nbsp;</li>
<li><a href="#method_summary">Method</a></li>
</ul>
<ul class="subNavList">
<li>Detail:&nbsp;</li>
<li>Field&nbsp;|&nbsp;</li>
<li><a href="#constructor_detail">Constr</a>&nbsp;|&nbsp;</li>
<li><a href="#method_detail">Method</a></li>
</ul>
</div>
<a name="skip-navbar_top">
<!--   -->
</a></div>
<!-- ========= END OF TOP NAVBAR ========= -->
<!-- ======== START OF CLASS DATA ======== -->
<div class="header">
<div class="subTitle">com.googlecode.catchexception</div>
<h2 title="Class CatchException" class="title">Class CatchException</h2>
</div>
<div class="contentContainer">
<ul class="inheritance">
<li><a href="http://docs.oracle.com/javase/6/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">java.lang.Object</a></li>
<li>
<ul class="inheritance">
<li>com.googlecode.catchexception.CatchException</li>
</ul>
</li>
</ul>
<div class="description">
<ul class="blockList">
<li class="blockList">
<hr>
<br>
<pre>public class <a href="../../../src-html/com/googlecode/catchexception/CatchException.html#line.221">CatchException</a>
extends <a href="http://docs.oracle.com/javase/6/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">Object</a></pre>
<div class="block">The methods of this class catch and verify exceptions in <em>a single line of
 code</em> and make them available for further analysis.
 <p>
 This Javadoc content is also available on the <a
 href="http://code.google.com/p/catch-exception/" >catch-exception</a> web
 page.
 
 <h1>Documentation</h1>
 <p>
 <b> <a href="#1">1. How to use catch-exception?</a><br/>
 <a href="#2">2. What is this stuff actually good for?</a> <br/>
 <a href="#3">3. How does it work internally?</a><br/>
 <a href="#4">4. When is the caught exception reset?</a><br/>
 <a href="#5">5. My code throws a ClassCastException. Why?</a> <br/>
 <a href="#6">6. The exception is not caught. Why?</a> <br/>
 <a href="#7">7. Do I have to care about memory leaks?</a> <br/>
 <a href="#8">8. The caught exception is not available in another thread.
 Why?</a><br/>
 <a href="#9">9. How do I catch an exception thrown by a static method?</a> <br/>
 <a href="#11">11. Can I catch errors instead of exceptions?</a> <br/>
 
 
 
 </b>
 <p>
 <h3 id="1">1. How to use catch-exception?</h3>
 <p>
 The most basic usage is:
 <code><pre class="prettyprint lang-java">import static com.googlecode.catchexception.CatchException.*;

// call customerService.prepareBilling(Prize.Zero)
// and catch the exception if any is thrown 
catchException(customerService).prepareBilling(Prize.Zero);

// assert that an IllegalArgumentException was thrown
assert caughtException() instanceof IllegalArgumentException;</pre></code>
 <p>
 You can combine the two lines of code in a single one if you like:
 <code><pre class="prettyprint lang-java">// call customerService.prepareBilling(Prize.Zero)
// and throw an ExceptionNotThrownAssertionError if
// the expected exception is not thrown 
verifyException(customerService, IllegalArgumentException.class).prepareBilling(Prize.Zero);</pre></code>
 There is a minor difference between both variants. In the first variant you
 must start the JVM with option <code>-ea</code> to enable the assertion. The
 second variant does not use JDK assertions and ,therefore, always verifies
 the caught exception.
 <p>
 A third variant allows you to select the type of exceptions you want to catch
 (no verification involved):
 <code><pre class="prettyprint lang-java">// catch IllegalArgumentExceptions but no other exceptions 
catchException(customerService, IllegalArgumentException.class).prepareBilling(Prize.Zero);</pre></code>
 <p>
 The fourth and last variant verifies that some exception is thrown, i.e. the
 type of the exception does not matter:
 <code><pre class="prettyprint lang-java">verifyException(customerService).prepareBilling(Prize.Zero);</pre></code>
 <p>
 In all variants you can use <code>caughtException()</code> afterwards to
 inspect the caught exception.
 <p>
 Finally, there some alternative ways to catch and verify exceptions:
 <ul>
 <li><a href="../../../com/googlecode/catchexception/apis/CatchExceptionBdd.html" title="class in com.googlecode.catchexception.apis"><code>CatchExceptionBdd</code></a> - a BDD-like approach,
 <li> <a href="../../../com/googlecode/catchexception/apis/CatchExceptionHamcrestMatchers.html" title="class in com.googlecode.catchexception.apis"><code>CatchExceptionHamcrestMatchers</code></a> - Hamcrest assertions
 </ul>
 <h3 id="2">2. What is this stuff actually good for?</h3>
 <p>
 This class targets concise and robust code in tests. Dadid Saff, a commiter
 to JUnit, has <a
 href="http://shareandenjoy.saff.net/2006/12/assertthrownexception_20.html"
 >discussed</a> this approach in 2007. Let me summarize the arguments here.
 <p>
 There are two advantages of the approach proposed here in comparison to the
 use of try/catch blocks.
 <ul>
 <li>The test is more concise and easier to read.
 <li>The test cannot be corrupted by a missing assertion. Assume you forgot to
 type <code>fail()</code> behind the method call that is expected to throw an
 exception.
 </ul>
 <p>
 There are also some advantages of this approach in comparison to test
 runner-specific mechanisms that catch and verify exceptions.
 <ul>
 <li>A single test can verify more than one thrown exception.
 <li>The test can verify the properties of the thrown exception after the
 exception is caught.
 <li>The test can specify by which method call the exception must be thrown.
 <li>The test does not depend on a specific test runner (JUnit4, TestNG).
 </ul>
 <p>
 <h3 id="3">3. How does it work internally?</h3>
 <p>
 The method <code>catchException(obj)</code> wraps the given object with a
 proxy that catches the exception, then (optionally) verifies the exception,
 and finally attaches the exception to the current <a
 name="threadlocal">thread</a> for further analysis. The <a
 href="#proxies">known limitations</a> for proxies apply.
 <p>
 Is both memory consumption and runtime a concern for you? Then use try/catch
 blocks instead of this class. Because in this case the creation of proxies is
 an unnecessary overhead. If only either memory consumption or runtime is an
 issue for you, feel free to configure the cache of the underlying proxy
 factories as appropriate.
 <h3 id="4">4. When is the caught exception reset?</h3>
 <p>
 The Method <a href="../../../com/googlecode/catchexception/CatchException.html#caughtException()"><code>caughtException()</code></a> returns the exception thrown by the
 last method call on a proxied object in the current thread, i.e. it is reset
 by calling a method on the proxied object. If the called method has not
 thrown an exception, <code>caughtException()</code> returns null.
 <p>
 To reset the caught exception manually, call <a href="../../../com/googlecode/catchexception/CatchException.html#resetCaughtException()"><code>resetCaughtException()</code></a>.
 At the moment there is no way to reset exceptions that have been caught in
 other threads.
 <h3 id="5"><a name="proxies" />5. My code throws a ClassCastException. Why?</h3>
 <p>
 Example:
 <code><pre class="prettyprint lang-java">StringBuilder sb = new StringBuilder();
catchException(sb).charAt(-2); // throws ClassCastException</pre></code>
 <p>
 Probably you have tested a final class. Proxy factories usually try to
 subclass the type of the proxied object. This is not possible if the original
 class is final. But there is a way out. If the tested method belongs to an
 interface, then you can cast the argument (here: <code>sb</code>) to that
 interface or ,easier, change the declared type of the argument to the
 interface type. This works because the created proxy is not longer required
 to have the same type as the original class but it must only have the same
 interface.
 <code><pre class="prettyprint lang-java">// first variant
StringBuilder sb = new StringBuilder();
catchException((CharSequence) sb).charAt(-2); // works fine

// second variant
CharSequence sb = new StringBuilder();
catchException(sb).charAt(-2); // works fine</pre></code> If the tested
 method does no belong to an interface fall back to the try/catch-blocks or
 use <a
 href="http://code.google.com/p/catch-exception/wiki/Dependencies">Powermock
 </a>.
 <code><pre class="prettyprint lang-java">// example for
 PowerMock with JUnit4
&#064;RunWith(PowerMockRunner.class)
&#064;PrepareForTest({ MyFinalType.class })
public class MyTest {
</pre></code>
 <h3 id="6">6. The exception is not caught. Why?</h3>
 <p>
 Example:
 <code><pre class="prettyprint lang-java">ServiceImpl impl = new ServiceImpl();
catchException(impl).do(); // do() is a final method that throws an exception</pre></code>
 <p>
 Probably you have tested a final method. If that tested method belongs to an
 interface you could use <a href="../../../com/googlecode/catchexception/CatchException.html#interfaces(T)"><code>interfaces(Object)</code></a> to fix that problem. But
 then the syntax starts to become ugly.
 <code><pre class="prettyprint lang-java">Service api = new ServiceImpl();
catchException(interfaces(api)).do(); // works fine</pre></code> I recommend
 to use try/catch blocks in such cases.
 
 <h3 id="7">7. Do I have to care about memory leaks?</h3>
 <p>
 This library uses a <a href="http://docs.oracle.com/javase/6/docs/api/java/lang/ThreadLocal.html?is-external=true" title="class or interface in java.lang"><code>ThreadLocal</code></a>. ThreadLocals are known to cause
 memory leaks if they refer to a class the garbage collector would like to
 collect. If you use this library only for testing, then memory leaks do not
 worry you. If you use this library for other purposes than testing, you
 should care.
 <p>
 <h3 id="8">8. The caught exception is not available in another thread. Why?</h3>
 <p>
 The caught exception is saved <a href="#threadlocal">at the thread</a> the
 exception is thrown in. This is the reason the exception is not visible
 within any other thread.
 <h3 id="9">9. How do I catch an exception thrown by a static method?</h3>
 <p>
 Unfortunately, catch-exception does not support this. Fall back on try/catch
 blocks.
 <h3 id="10">10. Is there a way to get rid of the throws clause in my test
 method?</h3>
 <p>
 Example:
 <code><pre class="prettyprint lang-java">public void testSomething() throws Exception {
    ...
    catchException(obj).do(); // do() throws a checked exception</pre></code> No,
 although the exception is always caught you cannot omit the throws clause in
 your test method.
 <h3 id="11">11. Can I catch errors instead of exceptions?</h3>
 <p>
 Yes, have a look at
 <a href="../../../com/googlecode/catchexception/throwable/CatchThrowable.html" title="class in com.googlecode.catchexception.throwable"><code>CatchThrowable</code></a> (in module
 catch-throwable).</div>
<dl><dt><span class="strong">Since:</span></dt>
  <dd>16.09.2011</dd>
<dt><span class="strong">Author:</span></dt>
  <dd>rwoo</dd></dl>
</li>
</ul>
</div>
<div class="summary">
<ul class="blockList">
<li class="blockList">
<!-- ======== CONSTRUCTOR SUMMARY ======== -->
<ul class="blockList">
<li class="blockList"><a name="constructor_summary">
<!--   -->
</a>
<h3>Constructor Summary</h3>
<table class="overviewSummary" border="0" cellpadding="3" cellspacing="0" summary="Constructor Summary table, listing constructors, and an explanation">
<caption><span>Constructors</span><span class="tabEnd">&nbsp;</span></caption>
<tr>
<th class="colOne" scope="col">Constructor and Description</th>
</tr>
<tr class="altColor">
<td class="colOne"><code><strong><a href="../../../com/googlecode/catchexception/CatchException.html#CatchException()">CatchException</a></strong>()</code>&nbsp;</td>
</tr>
</table>
</li>
</ul>
<!-- ========== METHOD SUMMARY =========== -->
<ul class="blockList">
<li class="blockList"><a name="method_summary">
<!--   -->
</a>
<h3>Method Summary</h3>
<table class="overviewSummary" border="0" cellpadding="3" cellspacing="0" summary="Method Summary table, listing methods, and an explanation">
<caption><span>Methods</span><span class="tabEnd">&nbsp;</span></caption>
<tr>
<th class="colFirst" scope="col">Modifier and Type</th>
<th class="colLast" scope="col">Method and Description</th>
</tr>
<tr class="altColor">
<td class="colFirst"><code>static &lt;T&gt;&nbsp;T</code></td>
<td class="colLast"><code><strong><a href="../../../com/googlecode/catchexception/CatchException.html#catchException(T)">catchException</a></strong>(T&nbsp;obj)</code>
<div class="block">Use it to catch an exception and to get access to the thrown exception
 (for further verifications).</div>
</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><code>static &lt;T,E extends <a href="http://docs.oracle.com/javase/6/docs/api/java/lang/Exception.html?is-external=true" title="class or interface in java.lang">Exception</a>&gt;&nbsp;<br>T</code></td>
<td class="colLast"><code><strong><a href="../../../com/googlecode/catchexception/CatchException.html#catchException(T,%20java.lang.Class)">catchException</a></strong>(T&nbsp;obj,
                            <a href="http://docs.oracle.com/javase/6/docs/api/java/lang/Class.html?is-external=true" title="class or interface in java.lang">Class</a>&lt;E&gt;&nbsp;clazz)</code>
<div class="block">Use it to catch an exception of a specific type and to get access to the
 thrown exception (for further verifications).</div>
</td>
</tr>
<tr class="altColor">
<td class="colFirst"><code>static &lt;E extends <a href="http://docs.oracle.com/javase/6/docs/api/java/lang/Exception.html?is-external=true" title="class or interface in java.lang">Exception</a>&gt;&nbsp;<br>E</code></td>
<td class="colLast"><code><strong><a href="../../../com/googlecode/catchexception/CatchException.html#caughtException()">caughtException</a></strong>()</code>
<div class="block">Returns the exception caught during the last call on the proxied object
 in the current thread.</div>
</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><code>static &lt;T&gt;&nbsp;T</code></td>
<td class="colLast"><code><strong><a href="../../../com/googlecode/catchexception/CatchException.html#interfaces(T)">interfaces</a></strong>(T&nbsp;obj)</code>
<div class="block">Returns a proxy that implements all interfaces of the underlying object.</div>
</td>
</tr>
<tr class="altColor">
<td class="colFirst"><code>private static &lt;T,E extends <a href="http://docs.oracle.com/javase/6/docs/api/java/lang/Exception.html?is-external=true" title="class or interface in java.lang">Exception</a>&gt;&nbsp;<br>T</code></td>
<td class="colLast"><code><strong><a href="../../../com/googlecode/catchexception/CatchException.html#processException(T,%20java.lang.Class,%20boolean)">processException</a></strong>(T&nbsp;obj,
                                <a href="http://docs.oracle.com/javase/6/docs/api/java/lang/Class.html?is-external=true" title="class or interface in java.lang">Class</a>&lt;E&gt;&nbsp;exceptionClazz,
                                boolean&nbsp;assertException)</code>
<div class="block">Creates a proxy that processes exceptions thrown by the underlying
 object.</div>
</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><code>static void</code></td>
<td class="colLast"><code><strong><a href="../../../com/googlecode/catchexception/CatchException.html#resetCaughtException()">resetCaughtException</a></strong>()</code>
<div class="block">Sets the <a href="../../../com/googlecode/catchexception/CatchException.html#caughtException()"><code>caught exception</code></a> to null.</div>
</td>
</tr>
<tr class="altColor">
<td class="colFirst"><code>static &lt;T&gt;&nbsp;T</code></td>
<td class="colLast"><code><strong><a href="../../../com/googlecode/catchexception/CatchException.html#verifyException(T)">verifyException</a></strong>(T&nbsp;obj)</code>
<div class="block">Use it to verify that an exception is thrown and to get access to the
 thrown exception (for further verifications).</div>
</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><code>static &lt;T,E extends <a href="http://docs.oracle.com/javase/6/docs/api/java/lang/Exception.html?is-external=true" title="class or interface in java.lang">Exception</a>&gt;&nbsp;<br>T</code></td>
<td class="colLast"><code><strong><a href="../../../com/googlecode/catchexception/CatchException.html#verifyException(T,%20java.lang.Class)">verifyException</a></strong>(T&nbsp;obj,
                              <a href="http://docs.oracle.com/javase/6/docs/api/java/lang/Class.html?is-external=true" title="class or interface in java.lang">Class</a>&lt;E&gt;&nbsp;clazz)</code>
<div class="block">Use it to verify that an exception of specific type is thrown and to get
 access to the thrown exception (for further verifications).</div>
</td>
</tr>
</table>
<ul class="blockList">
<li class="blockList"><a name="methods_inherited_from_class_java.lang.Object">
<!--   -->
</a>
<h3>Methods inherited from class&nbsp;java.lang.<a href="http://docs.oracle.com/javase/6/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">Object</a></h3>
<code><a href="http://docs.oracle.com/javase/6/docs/api/java/lang/Object.html?is-external=true#clone()" title="class or interface in java.lang">clone</a>, <a href="http://docs.oracle.com/javase/6/docs/api/java/lang/Object.html?is-external=true#equals(java.lang.Object)" title="class or interface in java.lang">equals</a>, <a href="http://docs.oracle.com/javase/6/docs/api/java/lang/Object.html?is-external=true#finalize()" title="class or interface in java.lang">finalize</a>, <a href="http://docs.oracle.com/javase/6/docs/api/java/lang/Object.html?is-external=true#getClass()" title="class or interface in java.lang">getClass</a>, <a href="http://docs.oracle.com/javase/6/docs/api/java/lang/Object.html?is-external=true#hashCode()" title="class or interface in java.lang">hashCode</a>, <a href="http://docs.oracle.com/javase/6/docs/api/java/lang/Object.html?is-external=true#notify()" title="class or interface in java.lang">notify</a>, <a href="http://docs.oracle.com/javase/6/docs/api/java/lang/Object.html?is-external=true#notifyAll()" title="class or interface in java.lang">notifyAll</a>, <a href="http://docs.oracle.com/javase/6/docs/api/java/lang/Object.html?is-external=true#toString()" title="class or interface in java.lang">toString</a>, <a href="http://docs.oracle.com/javase/6/docs/api/java/lang/Object.html?is-external=true#wait()" title="class or interface in java.lang">wait</a>, <a href="http://docs.oracle.com/javase/6/docs/api/java/lang/Object.html?is-external=true#wait(long)" title="class or interface in java.lang">wait</a>, <a href="http://docs.oracle.com/javase/6/docs/api/java/lang/Object.html?is-external=true#wait(long,%20int)" title="class or interface in java.lang">wait</a></code></li>
</ul>
</li>
</ul>
</li>
</ul>
</div>
<div class="details">
<ul class="blockList">
<li class="blockList">
<!-- ========= CONSTRUCTOR DETAIL ======== -->
<ul class="blockList">
<li class="blockList"><a name="constructor_detail">
<!--   -->
</a>
<h3>Constructor Detail</h3>
<a name="CatchException()">
<!--   -->
</a>
<ul class="blockListLast">
<li class="blockList">
<h4>CatchException</h4>
<pre>public&nbsp;<a href="../../../src-html/com/googlecode/catchexception/CatchException.html#line.221">CatchException</a>()</pre>
</li>
</ul>
</li>
</ul>
<!-- ============ METHOD DETAIL ========== -->
<ul class="blockList">
<li class="blockList"><a name="method_detail">
<!--   -->
</a>
<h3>Method Detail</h3>
<a name="caughtException()">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>caughtException</h4>
<pre>public static&nbsp;&lt;E extends <a href="http://docs.oracle.com/javase/6/docs/api/java/lang/Exception.html?is-external=true" title="class or interface in java.lang">Exception</a>&gt;&nbsp;E&nbsp;<a href="../../../src-html/com/googlecode/catchexception/CatchException.html#line.238">caughtException</a>()</pre>
<div class="block">Returns the exception caught during the last call on the proxied object
 in the current thread.</div>
<dl><dt><span class="strong">Type Parameters:</span></dt><dd><code>E</code> - This type parameter makes some type casts redundant.</dd>
<dt><span class="strong">Returns:</span></dt><dd>Returns the exception caught during the last call on the proxied
         object in the current thread - if the call was made through a
         proxy that has been created via
         <a href="../../../com/googlecode/catchexception/CatchException.html#verifyException(T,%20java.lang.Class)"><code>verifyException()</code></a> or
         <a href="../../../com/googlecode/catchexception/CatchException.html#catchException(T,%20java.lang.Class)"><code>catchException()</code></a>. Returns
         null the proxy has not caught an exception. Returns null if the
         caught exception belongs to a class that is no longer
         <a href="http://docs.oracle.com/javase/6/docs/api/java/lang/ClassLoader.html?is-external=true" title="class or interface in java.lang"><code>loaded</code></a>.</dd></dl>
</li>
</ul>
<a name="verifyException(java.lang.Object)">
<!--   -->
</a><a name="verifyException(T)">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>verifyException</h4>
<pre>public static&nbsp;&lt;T&gt;&nbsp;T&nbsp;<a href="../../../src-html/com/googlecode/catchexception/CatchException.html#line.265">verifyException</a>(T&nbsp;obj)</pre>
<div class="block">Use it to verify that an exception is thrown and to get access to the
 thrown exception (for further verifications).
 <p>
 The following example verifies that obj.doX() throws a Exception:
 <code><pre class="prettyprint lang-java">verifyException(obj).doX(); // catch and verify
assert "foobar".equals(caughtException().getMessage()); // further analysis
</pre></code>
 <p>
 If <code>doX()</code> does not throw a <code>Exception</code>, then a
 <a href="../../../com/googlecode/catchexception/ExceptionNotThrownAssertionError.html" title="class in com.googlecode.catchexception"><code>ExceptionNotThrownAssertionError</code></a> is thrown. Otherwise the thrown
 exception can be retrieved via <a href="../../../com/googlecode/catchexception/CatchException.html#caughtException()"><code>caughtException()</code></a>.
 <p></div>
<dl><dt><span class="strong">Type Parameters:</span></dt><dd><code>T</code> - The type of the given <code>obj</code>.</dd><dt><span class="strong">Parameters:</span></dt><dd><code>obj</code> - The instance that shall be proxied. Must not be
            <code>null</code>.</dd>
<dt><span class="strong">Returns:</span></dt><dd>Returns an object that verifies that each invocation on the
         underlying object throws an exception.</dd></dl>
</li>
</ul>
<a name="verifyException(java.lang.Object,java.lang.Class)">
<!--   -->
</a><a name="verifyException(T, java.lang.Class)">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>verifyException</h4>
<pre>public static&nbsp;&lt;T,E extends <a href="http://docs.oracle.com/javase/6/docs/api/java/lang/Exception.html?is-external=true" title="class or interface in java.lang">Exception</a>&gt;&nbsp;T&nbsp;<a href="../../../src-html/com/googlecode/catchexception/CatchException.html#line.297">verifyException</a>(T&nbsp;obj,
                                        <a href="http://docs.oracle.com/javase/6/docs/api/java/lang/Class.html?is-external=true" title="class or interface in java.lang">Class</a>&lt;E&gt;&nbsp;clazz)</pre>
<div class="block">Use it to verify that an exception of specific type is thrown and to get
 access to the thrown exception (for further verifications).
 <p>
 The following example verifies that obj.doX() throws a MyException:
 <code><pre class="prettyprint lang-java">verifyException(obj, MyException.class).doX(); // catch and verify
assert "foobar".equals(caughtException().getMessage()); // further analysis
</pre></code>
 <p>
 If <code>doX()</code> does not throw a <code>MyException</code>, then a
 <a href="../../../com/googlecode/catchexception/ExceptionNotThrownAssertionError.html" title="class in com.googlecode.catchexception"><code>ExceptionNotThrownAssertionError</code></a> is thrown. Otherwise the thrown
 exception can be retrieved via <a href="../../../com/googlecode/catchexception/CatchException.html#caughtException()"><code>caughtException()</code></a>.
 <p></div>
<dl><dt><span class="strong">Type Parameters:</span></dt><dd><code>T</code> - The type of the given <code>obj</code>.</dd><dd><code>E</code> - The type of the exception that shall be caught.</dd><dt><span class="strong">Parameters:</span></dt><dd><code>obj</code> - The instance that shall be proxied. Must not be
            <code>null</code>.</dd><dd><code>clazz</code> - The type of the exception that shall be thrown by the
            underlying object. Must not be <code>null</code>.</dd>
<dt><span class="strong">Returns:</span></dt><dd>Returns an object that verifies that each invocation on the
         underlying object throws an exception of the given type.</dd></dl>
</li>
</ul>
<a name="catchException(java.lang.Object)">
<!--   -->
</a><a name="catchException(T)">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>catchException</h4>
<pre>public static&nbsp;&lt;T&gt;&nbsp;T&nbsp;<a href="../../../src-html/com/googlecode/catchexception/CatchException.html#line.328">catchException</a>(T&nbsp;obj)</pre>
<div class="block">Use it to catch an exception and to get access to the thrown exception
 (for further verifications).
 <p>
 In the following example you catch exceptions that are thrown by
 obj.doX():
 <code><pre class="prettyprint lang-java">catchException(obj).doX(); // catch
if (caughtException() != null) {
    assert "foobar".equals(caughtException().getMessage()); // further analysis
}</pre></code>
 If <code>doX()</code> throws a exception, then <a href="../../../com/googlecode/catchexception/CatchException.html#caughtException()"><code>caughtException()</code></a>
 will return the caught exception. If <code>doX()</code> does not throw a
 exception, then <a href="../../../com/googlecode/catchexception/CatchException.html#caughtException()"><code>caughtException()</code></a> will return <code>null</code>.
 <p></div>
<dl><dt><span class="strong">Type Parameters:</span></dt><dd><code>T</code> - The type of the given <code>obj</code>.</dd><dt><span class="strong">Parameters:</span></dt><dd><code>obj</code> - The instance that shall be proxied. Must not be
            <code>null</code>.</dd>
<dt><span class="strong">Returns:</span></dt><dd>Returns a proxy for the given object. The proxy catches
         exceptions of the given type when a method on the proxy is
         called.</dd></dl>
</li>
</ul>
<a name="catchException(java.lang.Object,java.lang.Class)">
<!--   -->
</a><a name="catchException(T, java.lang.Class)">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>catchException</h4>
<pre>public static&nbsp;&lt;T,E extends <a href="http://docs.oracle.com/javase/6/docs/api/java/lang/Exception.html?is-external=true" title="class or interface in java.lang">Exception</a>&gt;&nbsp;T&nbsp;<a href="../../../src-html/com/googlecode/catchexception/CatchException.html#line.367">catchException</a>(T&nbsp;obj,
                                       <a href="http://docs.oracle.com/javase/6/docs/api/java/lang/Class.html?is-external=true" title="class or interface in java.lang">Class</a>&lt;E&gt;&nbsp;clazz)</pre>
<div class="block">Use it to catch an exception of a specific type and to get access to the
 thrown exception (for further verifications).
 <p>
 In the following example you catch exceptions of type MyException that
 are thrown by obj.doX():
 <code><pre class="prettyprint lang-java">catchException(obj, MyException.class).doX(); // catch
if (caughtException() != null) {
    assert "foobar".equals(caughtException().getMessage()); // further analysis
}</pre></code>
 If <code>doX()</code> throws a <code>MyException</code>, then
 <a href="../../../com/googlecode/catchexception/CatchException.html#caughtException()"><code>caughtException()</code></a> will return the caught exception. If
 <code>doX()</code> does not throw a <code>MyException</code>, then
 <a href="../../../com/googlecode/catchexception/CatchException.html#caughtException()"><code>caughtException()</code></a> will return <code>null</code>. If
 <code>doX()</code> throws an exception of another type, i.e. not a
 subclass but another class, then this exception is not thrown and
 <a href="../../../com/googlecode/catchexception/CatchException.html#caughtException()"><code>caughtException()</code></a> will return <code>null</code>.
 <p></div>
<dl><dt><span class="strong">Type Parameters:</span></dt><dd><code>T</code> - The type of the given <code>obj</code>.</dd><dd><code>E</code> - The type of the exception that shall be caught.</dd><dt><span class="strong">Parameters:</span></dt><dd><code>obj</code> - The instance that shall be proxied. Must not be
            <code>null</code>.</dd><dd><code>clazz</code> - The type of the exception that shall be caught. Must not be
            <code>null</code>.</dd>
<dt><span class="strong">Returns:</span></dt><dd>Returns a proxy for the given object. The proxy catches
         exceptions of the given type when a method on the proxy is
         called.</dd></dl>
</li>
</ul>
<a name="processException(java.lang.Object,java.lang.Class,boolean)">
<!--   -->
</a><a name="processException(T, java.lang.Class, boolean)">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>processException</h4>
<pre>private static&nbsp;&lt;T,E extends <a href="http://docs.oracle.com/javase/6/docs/api/java/lang/Exception.html?is-external=true" title="class or interface in java.lang">Exception</a>&gt;&nbsp;T&nbsp;<a href="../../../src-html/com/googlecode/catchexception/CatchException.html#line.383">processException</a>(T&nbsp;obj,
                                         <a href="http://docs.oracle.com/javase/6/docs/api/java/lang/Class.html?is-external=true" title="class or interface in java.lang">Class</a>&lt;E&gt;&nbsp;exceptionClazz,
                                         boolean&nbsp;assertException)</pre>
<div class="block">Creates a proxy that processes exceptions thrown by the underlying
 object.
 <p>
 Delegates to
 <a href="../../../com/googlecode/catchexception/internal/SubclassProxyFactory.html#createProxy(java.lang.Class,%20org.mockito.cglib.proxy.MethodInterceptor)"><code>SubclassProxyFactory.createProxy(Class, MethodInterceptor)</code></a> which
 itself might delegate to
 <a href="../../../com/googlecode/catchexception/internal/InterfaceOnlyProxyFactory.html#createProxy(java.lang.Class,%20org.mockito.cglib.proxy.MethodInterceptor)"><code>InterfaceOnlyProxyFactory.createProxy(Class, MethodInterceptor)</code></a>.</div>
</li>
</ul>
<a name="interfaces(java.lang.Object)">
<!--   -->
</a><a name="interfaces(T)">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>interfaces</h4>
<pre>public static&nbsp;&lt;T&gt;&nbsp;T&nbsp;<a href="../../../src-html/com/googlecode/catchexception/CatchException.html#line.406">interfaces</a>(T&nbsp;obj)</pre>
<div class="block">Returns a proxy that implements all interfaces of the underlying object.</div>
<dl><dt><span class="strong">Type Parameters:</span></dt><dd><code>T</code> - must be an interface the object implements</dd><dt><span class="strong">Parameters:</span></dt><dd><code>obj</code> - the object that created proxy will delegate all calls to</dd>
<dt><span class="strong">Returns:</span></dt><dd>Returns a proxy that implements all interfaces of the underlying
         object and delegates all calls to that underlying object.</dd></dl>
</li>
</ul>
<a name="resetCaughtException()">
<!--   -->
</a>
<ul class="blockListLast">
<li class="blockList">
<h4>resetCaughtException</h4>
<pre>public static&nbsp;void&nbsp;<a href="../../../src-html/com/googlecode/catchexception/CatchException.html#line.426">resetCaughtException</a>()</pre>
<div class="block">Sets the <a href="../../../com/googlecode/catchexception/CatchException.html#caughtException()"><code>caught exception</code></a> to null. This does
 not affect exceptions saved at threads other than the current one.
 <p>
 Actually you probably never need to call this method because each method
 call on a proxied object in the current thread resets the caught
 exception. But if you want to improve test isolation or if you want to
 'clean up' after testing (to avoid memory leaks), call the method before
 or after testing.</div>
</li>
</ul>
</li>
</ul>
</li>
</ul>
</div>
</div>
<!-- ========= END OF CLASS DATA ========= -->
<!-- ======= START OF BOTTOM NAVBAR ====== -->
<div class="bottomNav"><a name="navbar_bottom">
<!--   -->
</a><a href="#skip-navbar_bottom" title="Skip navigation links"></a><a name="navbar_bottom_firstrow">
<!--   -->
</a>
<ul class="navList" title="Navigation">
<li><a href="../../../overview-summary.html">Overview</a></li>
<li><a href="package-summary.html">Package</a></li>
<li class="navBarCell1Rev">Class</li>
<li><a href="class-use/CatchException.html">Use</a></li>
<li><a href="package-tree.html">Tree</a></li>
<li><a href="../../../deprecated-list.html">Deprecated</a></li>
<li><a href="../../../index-all.html">Index</a></li>
<li><a href="../../../help-doc.html">Help</a></li>
</ul>
</div>
<div class="subNav">
<ul class="navList">
<li>Prev Class</li>
<li><a href="../../../com/googlecode/catchexception/ExceptionNotThrownAssertionError.html" title="class in com.googlecode.catchexception"><span class="strong">Next Class</span></a></li>
</ul>
<ul class="navList">
<li><a href="../../../index.html?com/googlecode/catchexception/CatchException.html" target="_top">Frames</a></li>
<li><a href="CatchException.html" target="_top">No Frames</a></li>
</ul>
<ul class="navList" id="allclasses_navbar_bottom">
<li><a href="../../../allclasses-noframe.html">All Classes</a></li>
</ul>
<div>
<script type="text/javascript"><!--
  allClassesLink = document.getElementById("allclasses_navbar_bottom");
  if(window==top) {
    allClassesLink.style.display = "block";
  }
  else {
    allClassesLink.style.display = "none";
  }
  //-->
</script>
</div>
<div>
<ul class="subNavList">
<li>Summary:&nbsp;</li>
<li>Nested&nbsp;|&nbsp;</li>
<li>Field&nbsp;|&nbsp;</li>
<li><a href="#constructor_summary">Constr</a>&nbsp;|&nbsp;</li>
<li><a href="#method_summary">Method</a></li>
</ul>
<ul class="subNavList">
<li>Detail:&nbsp;</li>
<li>Field&nbsp;|&nbsp;</li>
<li><a href="#constructor_detail">Constr</a>&nbsp;|&nbsp;</li>
<li><a href="#method_detail">Method</a></li>
</ul>
</div>
<a name="skip-navbar_bottom">
<!--   -->
</a></div>
<!-- ======== END OF BOTTOM NAVBAR ======= -->
<p class="legalCopy"><small>Copyright &#169; 2014. All rights reserved.</small></p>
</body>
</html>
